### PR TITLE
Show native structures work

### PR DESCRIPTION
**Pull request by khornberg**
Show that stringified objects can be returned to their native structures and used accordingly

### CODE REVIEW

**Comment by TayHobbs** [comment]
@khornberg No tests?

**Comment by khornberg** [comment]
Tests added
CI?

**Comment by TayHobbs** [comment]
@khornberg Nah.

Kind of nitpicky, but you added the assertions to the `Coverts specified files to a string` test, which doesn't really say what the assertions are testing. Would you mind moving these into another test with a correct name?

**Comment by khornberg** [comment]
done

**Comment by TayHobbs** [comment]
@khornberg Thank you very much.

**Pull request merged**
